WIP: add slice_traces, filter_fws_log and sharpen_fws_log
alt-lu/pywellcad pull request #126
Opened 2023-03-07 14:06 UTC by ArnaudCrl

2023-03-07 14:37 UTC, ArnaudCrl commented
I have not yet ran the tests. I'll remove the WIP once it's done.

2023-04-17 13:49 UTC, ArnaudCrl commented
The tests for sharpen_rgb_log and retinex_filter_rgb_log are not passing currently. It seems to be returning None instead of the Log.

2023-04-19 04:06 UTC, m-schubert requested changes
Just a couple of changes, please.

2023-04-19 04:06 UTC, m-schubert commented on wellcad/com/_borehole.py
> +    def cased_hole_ultrasonics(self, abiwavelet_log=None, zone_log=None, prompt_user=None, config=None):
Probably best to just call this `wavelet_log`, given it isn't exclusive to the ABI. If you want to keep the term ABI, go with `abi_wavelet_log`.

2023-04-19 04:06 UTC, m-schubert commented on wellcad/com/_borehole.py
> +            Path to a configuration file or a parameter string. The
Best to mark this as unused at the parameter level rather than below in the INI format documentation.

2023-04-19 04:06 UTC, m-schubert commented on wellcad/com/_borehole.py
> +                Not used
Don't bother describing the parameter if it isn't used. Just mention it isn't used at the top level.

2023-04-19 04:06 UTC, m-schubert commented on wellcad/com/_borehole.py
> +                end = 0  # in log units
Comments are `;`, not `#`. Also, are the double square brackets intentional?

2023-04-19 08:01 UTC, m-schubert approved these changes

2023-04-19 08:01 UTC, merged